pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { mavenCentral() }
}

rootProject.name = 'pact-rest-h2-sample'

def cdcFramework = file('../consumer-driven-contract-testing')
if (!cdcFramework.exists()) {
    cdcFramework = file('consumer-driven-contract-testing')
}
includeBuild(cdcFramework)